name: Branches

on:
  push:
    branches-ignore:
      - "main"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - run: test -z $(gofmt -l .)
        name: "gofmt"
