name: Main

on:
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - run: test -z $(gofmt -l .)
        name: "gofmt"

      - run: go build

  deploy:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: sousa-cluster
          location: europe-west2-a

      - uses: docker/setup-buildx-action@v1

      - run: gcloud auth configure-docker --quiet

      - run: make build

      - run: make push

      - run: make helm
